#! /bin/bash

function packet(){
	if $1 == "icmp";then
		ip=$(whiptail --title "icmp packet" --inputbox "please enter the dest ip" 8 39 3>&1 1>&2 2>&3)
		ping -c 4 $ip > icmp
		res=$(cat icmp)
		whiptail --title "icmp result" --msgbox "$res" 45 90
	fi
}

function storage() {
	text=$(bash -c $1)
    	whiptail --title "$1" --msgbox "$text" 50 110 
}
function networking(){
	case $1 in
		1)
			ports=$(ss -tulw | grep LISTEN | awk '{print $5}' | awk -F : '{gsub(/[^0-9 ]/,"",$2); print $2}'| uniq)
			whiptail --title "open ports" --msgbox "$ports" 45 90
		;;
		2)
			bash -c 'python net.py'
		;;
		3)
			proto=$(whiptail --title 'choose your protocol' --fb --menu "pick the protocol for the packet" 15 60 4 \
				"icmp" 'send a ping packet' \
				"dns" 'get the ip' \
				"http" 'send an http request' 3>&1 1>&2 2>&3)
			echo $proto
			packet $proto
		;;	
		esac		
}

function advancedMenu() {
    CHOMEN=$(whiptail --title "Advanced Menu" --fb --menu "Choose an option" 15 60 4 \
        "1" "inspect the stroage of you machine" \
        "2" "inspect the networking of your machine" \
        "3" "inpect you dnf/yum/apt repos" 3>&1 1>&2 2>&3)
    case $CHOMEN in
        1)
            
            STO=$(whiptail --title "storage" --menu --fb "choose the level you want to view" 15 60 4 \
		    "pvs" "physical discs" \
		    "vgs" "volume groups" \
		    "lvs" "logical volume" 3>&1 1>&2 2>&3)
	    storage $STO	
        ;;
        2)
            
            NET=$(whiptail --title "networking" --menu --fb "choose what is it you want to do" 15 60 4 \
		    "1" "check open ports" \
		    "2" "watch tcp wireshark style" \
		    "3" "craft and send packet" 3>&1 1>&2 2>&3)
	    networking $NET
        ;;
        3)
            echo $ADVSEL
            #whiptail --title "Option 1" --msgbox "You chose option 3. Exit status $?" 8 45
        ;;
    esac
}
advancedMenu
